### ISSUE TITLE
Error when running 'pdst_raw_to_tidy.R'

### ISSUE THREAD

**Issue by PieterjanVerhelst** [PieterjanVerhelst/eel-pdst-analysis#28]
When I run the code `pdst_raw_to_tidy.R` to create sensor and daylog files from the raw data, I get an error: `Error: StopIteration`. I done' understand why. This error happens with an older data file than what the code was developed for. Here is a download link to a file causing the error (`A03486_25-03-2009`) and a recent file (`A17480_27-01-2020`) for comparison. 
https://we.tl/t-riRYAKGDTO

Both files need to be placed in the raw data folder `.data/raw/`.

I am currently working on the branch `dvm-analysis`.

**Comment by damianooldoni** [comment]
Probably similar to https://github.com/PieterjanVerhelst/shad-dst-analysis/issues/1.

Update: no, it's not the same. Data of pdst model are not merging pressure and temperature sensor data in one data block. They are still one below each other.

**Comment by damianooldoni** [comment]
Error probably due to empty Data Block 2: see from line 651172 in `A03486_25-03-2009.csv`.

**Comment by damianooldoni** [comment]
However, the first encountered problem is at the very beginning while reading daylog section. 

The string `"Total Days Alive"` is not present in `A03486_25-03-2009.csv`.

My question for @PieterjanVerhelst: must we support old files as `A03486_25-03-2009.csv`? In shad-dst you decided to update the functions to new format. But this is another tag model and another research scenario.

**Comment by PieterjanVerhelst** [comment]
@damianooldoni indeed, temperature blocks is empty while the daylogs show measurements. Weird... I guess in such a case the second sensor (here temperature) should be left out in the sensorlog file.

I would support older files as well. These tags can go adrift at sea for some years before being retrieved. I am not sure how to define this in the script. Any suggestions?

**Comment by damianooldoni** [comment]
I would write different functions for old/new format depending on the last four digits of the tagID which indicates the manufacturing year, I suppose. But to be totally sure that the year is enough to define the format we need to check other files. Do you have other files from 2009, 2020 or any other year in between?

**Comment by PieterjanVerhelst** [comment]
yes, and indeed, for the cefas technology tags the year is in the file name. For other datasets that is not the case. For those a specific line in the raw dataset could be checked. Here is an example dataset by star-oddi.
[2U15525.zip](https://github.com/PieterjanVerhelst/eel-pdst-analysis/files/14573886/2U15525.zip)

**Comment by damianooldoni** [comment]
Indeed, we must read the version in the file itself instead of using the year in filename. The same strategy for the tagID (we do that already).

Note that `A17480_27-01-2020.csv` contains the line `File created using G5 Host version 7.6.2.0`, which allows us to retrieve the version of G5 Host model we must support, i.e. `7.6.2.0`.

A line follows with a comment: `Comment :- Downloaded on 27-01-2020`. So, the year in filename seems the download date: a reason more to use the version embedded in the file.
 
About `A03486_25-03-2009.csv`, this file starts with the comment line (!): `Comment :- NOTE times are BST, as tag clock was set to BST`. Strange that a datafile starts with a comment: are you sure nobody modified this csv file? Also I see  these two lines a little below:

```
Deployed by Host Version, 3. 9. 0
Downloaded by Host Version,5.7.0
```

Which indicate that the file has version `5.7.0` probably. Still, I find strange there is no information about it at the very beginning of the file. Any input, comment welcome!

**Comment by PieterjanVerhelst** [comment]
aah indeed, we can check the version in the file! But like you write in your comment: it can be that a tag was deployed at a certain software version, but that the software was updated by the time the tag was retrieved, resulting in another software version during download.

I don't think the `A03486_25-03-2009.csv` file was adjusted. I would think that the software at that time indicated the time zone at which the clock was set when the tag was deployed before it was attached to a fish.

Does this make sense to you?

**Comment by damianooldoni** [comment]
> I don't think the A03486_25-03-2009.csv file was adjusted.

Ok. Then, the question is: which is the version of the file? `3. 9. 0` (deploy) or `5.7.0` (download)? I think the second one as it is during a download that a csv file is created. But you probably know better than me about this. Please, let me know.

Still, it makes the code slightly more complicated to retrieve the version in different places of the file.

Question is: can you check the version of all your tag sensor data? Are there any other versions to support?

**Comment by PieterjanVerhelst** [comment]
Indeed, I would think that the version of the file is the version during download.

I likely have files with different (download) software versions, so I can provide you some examples.

**Comment by PieterjanVerhelst** [comment]
@damianooldoni I just checked and regarding the 'cefas technology' tags of type 'pdst' I have datasets from 2012 and 2018 - 2020, but all were installed or downloaded (can't find the distinction) with firmware version 3. The older file you are testing was under firmware 2 and dated from 2008. Here is a wetransfer link to data of 2012 and 2018: https://we.tl/t-T2PytIQps3
Note that the code was developed to process these files and it worked. And still works I suppose, but haven't needed it in this repo for recent files in a year.

**Comment by damianooldoni** [comment]
One of the two files in the wetransfer package is not from 2018, but 2019. And it has both the same software version (`7.6.2.0`) and firmware version (`3`) as the file `A17480_27-01-2020.csv` you sent me in the first comment above (https://github.com/PieterjanVerhelst/eel-pdst-analysis/issues/28#issue-2154931284). Probably do you wanted to send me another file?

You speak about firmware version instead of software version. They are two different things. Do you think the differences are due to a difference in the firmware version? Here below a scheme with firmware and software specifications to discover what is the (combination of) specification(s) which make the files different.

File | Firmware Version No | Firmware Build Level | File created using G5 Host version | Shipped | Deployment
--- | --- | --- | --- | --- | ---
A17480_27-01-2020.csv | 3 | 80 | 7.6.2.0 | 1.1.0 | 7.3.0 (twice)
A16031_08-11-2019.csv | 3 | 80 | 7.6.2.0 | 1.0.8 | 7.3.0 (thrice)
A09374_09-01-2013.CSV | 3 | 40 | missing | 6.5.5 | 6.5.0
A03486_25-03-2009.csv | 2 | 70 | missing (but "Downloaded by Host Version,5.7.0") | missing | Deployed by Host Version, 3. 9. 0
A15881_04-09-2020.csv (acceleration) | 3 | 80 | 7.6.2.0 | 1.0.5 | 7.2.0 (5/9/2018 23:11), 7.3.0 (6/9/2018 0:00)

I would exclude the software version of the tag as shipped and as deployed: they can even be deployed using different versions, for example. I find very strange that `A09374_09-01-2013.CSV` has no version under "File created using ..." or "Downloaded by ...". Notice also that the extension is uppercase, while all others are lowercase.

**Comment by PieterjanVerhelst** [comment]
Indeed, one of the files is from 2019 instead of 2018 but it doesn't make a difference. They are from the same batch and installed under the same software version. File 'A15881_04-09-2020.csv' is indeed a recent one, so no wonder it is the same as those I sent you. However, that one has the acceleration data. So now you have all the types of PDST datasets that I have.

**Comment by damianooldoni** [comment]
I think this issue is solved in branch [improve-reading-functionality](https://github.com/PieterjanVerhelst/eel-pdst-analysis/tree/improve-reading-functionality). You can test it already. 
It works with files with firmware version /build level 2.70 and 3.80. But it can be easily modified at https://github.com/PieterjanVerhelst/eel-pdst-analysis/blob/improve-reading-functionality/src/pdst_functions.R#L85-L90

I didn't open a PR just because I want to solve also #29.

**Comment by PieterjanVerhelst** [comment]
It works perfect for files like the example I sent you which have firmware version 2.70. However, I now see that I have a few files on firmware version 3.40 😒 . So the code needs another level I suppose. I will send you a wetransfer link in our institute chat with the file. 
I think the different (meta) data formats according to different firmware versions is definitely something we need to tackle at manufacturer level and discuss during our upcoming 'ETN & BioFlow' meeting.

**Comment by damianooldoni** [comment]
@PieterjanVerhelst: the reading of files with firmware 3, build level 80 is now possible. Actually it's the same as the one for 3.80. Check it, please.

**Comment by PieterjanVerhelst** [comment]
@damianooldoni code runs on all the available datasets 👏 !
